#!/bin/sh
#
# Simple script to setup git hook

set -e

HOOK=`pwd`

if [ "$1" == "" ]
then
  echo 'No directory provided, assuming the parent directory holds puppet repos.'
  LOCATION=`dirname ${HOOK}`
else
  LOCATION="$1"
fi

echo "Installing hook to ${LOCATION}"
cd $LOCATION
ln -sfn "${HOOK}/pre-commit" .git/hooks/pre-commit

echo 'Setting the executable bit on the hook.'
cd $HOOK
chmod +x pre-commit

echo 'Installation complete.'
echo ''
